package service.cleanup;

import base.BaseSFDCTest;
import com.sforce.soap.enterprise.sobject.*;
import com.sforce.ws.ConnectionException;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collection;
import java.util.List;
import java.util.Set;

import static utilities.Constants.USER;
import static io.qameta.allure.Allure.step;
import static java.util.stream.Collectors.joining;
import static java.util.stream.Collectors.toSet;

/**
 * Special task for removing SFDC records generated by automated tests from the test sandbox.
 */
public class CleanUp extends BaseSFDCTest {
    private static final Logger LOGGER = LoggerFactory.getLogger(CleanUp.class);

    private List<Lead> leadsToConvert;
    private Set<String> convertedAccountsIds;
    private Set<String> allTestAccountIds;
    private String allTestAccountIdsListAsString;

    @Test
    @DisplayName("Clean up SFDC records generated by the Automation tests")
    public void test() {
        step("1. Search for test Leads created for conversion and their converted Accounts", () -> {
            leadsToConvert = enterpriseConnectionUtils.query(
                    "SELECT Id, ConvertedAccountId " +
                            "FROM Lead " +
                            "WHERE CreatedBy.Username = '" + USER + "'",
                    Lead.class);
            LOGGER.info("Found {} test Leads", leadsToConvert.size());

            convertedAccountsIds = leadsToConvert.stream()
                    .map(Lead::getConvertedAccountId)
                    .filter(id -> id != null)
                    .collect(toSet());
            LOGGER.info("Found {} accounts converted from test Leads", convertedAccountsIds.size());
        });

        step("2. Search for existing test Accounts", () -> {
            var accounts = enterpriseConnectionUtils.query(
                    "SELECT Id " +
                            "FROM Account " +
                            "WHERE CreatedBy.Username = '" + USER + "'",
                    Account.class);
            LOGGER.info("Found {} test Accounts", accounts.size());

            step("Merge existing test Accounts with Accounts converted from test Leads " +
                    "into 'All test Accounts' list", () -> {
                allTestAccountIds = accounts.stream()
                        .map(Account::getId)
                        .collect(toSet());
                allTestAccountIds.addAll(convertedAccountsIds);

                //  As a list for filtering SOQL queries. E.g. ('Id1','Id2','Id3') or ('') if there are no test accounts
                allTestAccountIdsListAsString = allTestAccountIds.stream()
                        .collect(joining("','", "('", "')"));
            });
        });

        if (allTestAccountIds.isEmpty()) {
            LOGGER.info("Test accounts are not found! Terminating test execution...");
            return;
        }

        step("3. Delete Area Code Line Items related to all test Accounts", () -> {
            var areaCodeLineItems = enterpriseConnectionUtils.query(
                    "SELECT Id " +
                            "FROM Area_Code_Line_Item__c " +
                            "WHERE Quote_Line_Item__r.Quote.AccountId IN " + allTestAccountIdsListAsString,
                    Area_Code_Line_Item__c.class);
            LOGGER.info("Found {} Area Code Line Items related to test Accounts", areaCodeLineItems.size());

            deleteByBatches(areaCodeLineItems);
        });

        step("4. Delete Cases related to all test Accounts", () -> {
            var cases = enterpriseConnectionUtils.query(
                    "SELECT Id " +
                            "FROM Case " +
                            "WHERE AccountId IN " + allTestAccountIdsListAsString,
                    Case.class);
            LOGGER.info("Found {} Cases related to test Accounts", cases.size());

            deleteByBatches(cases);
        });

        step("5. Delete Approvals related to all test Accounts", () -> {
            var approvals = enterpriseConnectionUtils.query(
                    "SELECT Id " +
                            "FROM Approval__c " +
                            "WHERE Account__c IN " + allTestAccountIdsListAsString,
                    Approval__c.class);
            LOGGER.info("Found {} Approvals related to test Accounts", approvals.size());

            deleteByBatches(approvals);
        });

        step("6. Delete Contracts related to all test Accounts", () -> {
            var contracts = enterpriseConnectionUtils.query(
                    "SELECT Id " +
                            "FROM Contract " +
                            "WHERE AccountId IN " + allTestAccountIdsListAsString,
                    Contract.class);
            LOGGER.info("Found {} Contracts related to test Accounts", contracts.size());

            deleteByBatches(contracts);
        });

        step("7. Delete Closed Opportunities related to all test Accounts", () -> {
            var closedWonOpportunities = enterpriseConnectionUtils.query(
                    "SELECT Id " +
                            "FROM Opportunity " +
                            "WHERE IsClosed = true " +
                            "AND AccountId IN " + allTestAccountIdsListAsString,
                    Opportunity.class);
            LOGGER.info("Found {} Closed Opportunities related to test Accounts", closedWonOpportunities.size());

            deleteByBatches(closedWonOpportunities);
        });

        step("8. Delete test Leads created for conversion", () -> {
            LOGGER.info("Deleting test Leads created for conversion...");
            deleteByBatches(leadsToConvert);
        });

        step("9. Delete created Partner Leads related to all test Accounts", () -> {
            var createdPartnerLeads = enterpriseConnectionUtils.query(
                    "SELECT Id " +
                            "FROM Lead " +
                            "WHERE Partner_Account__c IN " + allTestAccountIdsListAsString,
                    Lead.class);
            LOGGER.info("Found {} created Partner Leads related to test Accounts", createdPartnerLeads.size());

            deleteByBatches(createdPartnerLeads);
        });

        step("10. Delete all Account Relation objects related to all test Accounts", () -> {
            var createdAccountRelations = enterpriseConnectionUtils.query(
                    "SELECT Id " +
                            "FROM AccountRelation__c " +
                            "WHERE Parent_Account__c IN " + allTestAccountIdsListAsString + " " +
                            "OR Child_Account__c IN " + allTestAccountIdsListAsString,
                    AccountRelation__c.class);
            LOGGER.info("Found {} created Account Relation objects related to test Accounts",
                    createdAccountRelations.size());

            deleteByBatches(createdAccountRelations);
        });

        step("11. Delete all Service Account objects related to all test Accounts", () -> {
            var createdServiceAccounts = enterpriseConnectionUtils.query(
                    "SELECT Id " +
                            "FROM Package__c " +
                            "WHERE Account__c IN " + allTestAccountIdsListAsString,
                    Package__c.class);
            LOGGER.info("Found {} created Service Account objects related to test Accounts",
                    createdServiceAccounts.size());

            deleteByBatches(createdServiceAccounts);
        });

        step("12. Delete all uploaded file attachments created by test user", () -> {
            var createdAttachments = enterpriseConnectionUtils.query(
                    "SELECT Id " +
                            "FROM ContentDocument " +
                            "WHERE CreatedBy.Username = '" + USER + "'",
                    ContentDocument.class);
            LOGGER.info("Found {} created ContentDocument objects uploaded by the test user",
                    createdAttachments.size());

            deleteByBatches(createdAttachments);
        });

        step("13. Delete all test Accounts", () -> {
            LOGGER.info("Deleting test Accounts...");
            deleteByBatches(allTestAccountIds);
        });
    }

    /**
     * Delete SObjects by batches of the fixed size using their IDs.
     *
     * @param sObjectIds set of IDs for SObjects that need to be deleted
     * @throws ConnectionException in case of errors while accessing API
     */
    private void deleteByBatches(Set<String> sObjectIds) throws ConnectionException {
        int batchLimitOnDelete = 200;   //  limit on delete by IDs operation since API v.7.0
        while (!sObjectIds.isEmpty()) {
            var elementsBatch = sObjectIds.stream()
                    .limit(batchLimitOnDelete)
                    .collect(toSet());
            sObjectIds.removeAll(elementsBatch);

            enterpriseConnectionUtils.deleteByIds(elementsBatch);

            LOGGER.info("Successfully deleted a batch of {} SObject(s): {}",
                    elementsBatch.size(), elementsBatch);
            LOGGER.info("Remaining number of SObjects to delete: " + sObjectIds.size());
        }
    }

    /**
     * Delete SObjects by batches of the fixed size.
     *
     * @param sObjects collection of SObjects that need to be deleted
     * @param <T>      any SObject type, like Lead, Account, Contact, Opportunity...
     * @throws ConnectionException in case of errors while accessing API
     */
    private <T extends SObject> void deleteByBatches(Collection<T> sObjects) throws ConnectionException {
        var ids = sObjects.stream()
                .map(SObject::getId)
                .collect(toSet());

        deleteByBatches(ids);
    }
}
