package page.opportunity.ngbsquotingwizard.modal;

import page.opportunity.ngbsquotingwizard.NGBSQuotingWizardPage;
import com.codeborne.selenide.ElementsCollection;
import com.codeborne.selenide.SelenideElement;

import static com.codeborne.selenide.Condition.attribute;
import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.$;

/**
 * Modal window in {@link NGBSQuotingWizardPage} ("Quote" tab)
 * activated by clicking on "Generate PDF" button.
 * <p>
 * Some or all PDF templates could be selected from the list.
 * Then, PDF Templates could be generated by clicking on "Generate and Preview" button.
 * </p>
 */
public class PDFGenerateModal {
    public static final String NO_AVAILABLE_TEMPLATES_MESSAGE = "No available templates";

    private final SelenideElement dialogContainer = $("pdf-select-template");

    public final ElementsCollection templateCheckboxes = dialogContainer.$$(".slds-checkbox.ng-star-inserted");
    public final ElementsCollection msaRadioButtons = dialogContainer.$$("[for^='template-radio']");
    public final ElementsCollection pdfOptionsRadioButtons = dialogContainer.$$("input[name='templates']");
    public final ElementsCollection pdfPreselectedTemplateNames =
            dialogContainer.$$(".slds-checkbox > input:disabled + label");
    public final ElementsCollection pdfNotselectedTemplateNames =
            dialogContainer.$$(".slds-checkbox > input:enabled + label");
    public final ElementsCollection pdfAllTemplateNames =
            dialogContainer.$$("span.slds-form-element__label");
    public final SelenideElement infoMessage = dialogContainer.$("p");

    //  Buttons (footer)
    public final SelenideElement generateAndPreviewPDFButton = dialogContainer.$(byText("Generate and Preview"));
    public final SelenideElement cancelButton = dialogContainer.$(byText("Cancel"));

    /**
     * Select all PDF templates and mark them checked.
     * Then, click on "Generate and Preview" button to open {@link ConfigurePlaybooksModal}
     */
    public void selectAllPDFTemplates() {
        for (var button : pdfOptionsRadioButtons.exclude(attribute("disabled"))) {
            button.sibling(0).click();
        }
        generateAndPreviewPDFButton.click();
    }
}
